import { existsSync, readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";

const ROOT = resolve(import.meta.dirname, "..", "..");
const PACKAGE_JSON = resolve(ROOT, "package.json");

function log(step: string, msg: string) {
  console.log(`\n[${step}] ${msg}`);
}

function run(cmd: string, args: string[]) {
  console.log(`> ${cmd} ${args.join(" ")}`);
  const result = spawnSync(cmd, args, {
    cwd: ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    console.error(`\nCommand failed: ${cmd} ${args.join(" ")}`);
    process.exit(result.status ?? 1);
  }
}

function fixNpmrc() {
  const npmrcPath = resolve(ROOT, ".npmrc");
  if (!existsSync(npmrcPath)) return;
  const content = readFileSync(npmrcPath, "utf8");
  const cleaned = content
    .split(/\r?\n/)
    .filter((line) => !/^\s*ignore-scripts\s*=/i.test(line))
    .join("\n")
    .trim();
  if (cleaned === content.trim()) return;
  if (cleaned.length === 0) {
    unlinkSync(npmrcPath);
    log("FIX", "Removed .npmrc (was forcing ignore-scripts=true)");
  } else {
    writeFileSync(npmrcPath, cleaned + "\n");
    log("FIX", "Removed ignore-scripts=true from .npmrc");
  }
}

function ensureEnv() {
  const envPath = resolve(ROOT, ".env");
  if (existsSync(envPath)) {
    log("ENV", ".env already exists — leaving it alone");
    return;
  }
  const sessionSecret = randomBytes(32).toString("hex");
  const content = [
    "# Auto-generated by setup. Edit DATABASE_URL to match your local Postgres.",
    "DATABASE_URL=postgres://estimator:changeme@localhost:5432/cable_estimator",
    `SESSION_SECRET=${sessionSecret}`,
    "NODE_ENV=development",
    "PORT=8080",
    "",
  ].join("\n");
  writeFileSync(envPath, content);
  log("ENV", "Created .env with default values + random SESSION_SECRET");
  console.log(
    "      Edit .env if your Postgres user/password/database are different.",
  );
}

function disablePreinstallTemporarily() {
  const original = readFileSync(PACKAGE_JSON, "utf8");
  const patched = original.replace(
    /"preinstall"\s*:\s*"[^"]*"/,
    '"preinstall": "node -e \"process.exit(0)\""',
  );
  if (patched === original) {
    throw new Error("Could not find root preinstall script to patch.");
  }
  writeFileSync(PACKAGE_JSON, patched);
  return () => writeFileSync(PACKAGE_JSON, original);
}

console.log("Cable Estimator — Local Setup");
console.log("==============================");

log("STEP 1/4", "Fixing .npmrc if needed");
fixNpmrc();

log("STEP 2/4", "Creating .env if missing");
ensureEnv();

log("STEP 3/4", "Installing dependencies (this may take 1-2 minutes)");
const restorePackageJson = disablePreinstallTemporarily();
try {
  run("pnpm", ["install"]);
} finally {
  restorePackageJson();
}

log("STEP 4/4", "Pushing database schema");
run("pnpm", ["--filter", "@workspace/db", "run", "push"]);

console.log("\n==============================");
console.log("Setup complete!");
console.log("");
console.log("Next: run start.cmd (Windows) or ./start.sh (macOS/Linux)");
console.log("to launch the API server and web app together.");
